### ADD
POST {{baseUrl}}/chat
Content-Type: application/json
secret: {{rootSecret}}

{
  "title": "firstGroup",
  "userIDs": "[1, 3]",
  "isGroup": true
}

### GET
GET {{baseUrl}}/chat?start=0&step=5
Content-Type: application/json
secret: {{rootSecret}}