### ADD
POST {{baseUrl}}/chat
Content-Type: application/json
secret: {{localRootSecret}}

{
  "title": "first group",
  "userIDs": "[3, 4]",
  "isGroup": true
}

### GET
GET {{baseUrl}}/chat?start=0&step=5&chatID=16
Content-Type: application/json
secret: {{localRootSecret}}