### ADD
POST {{baseUrl}}/message
Content-Type: application/json
secret: {{localRootSecret}}

{
  "chatID": 2,
  "content": "replyContent",
  "reply": "14"
}

### EDIT
PATCH {{baseUrl}}/message
Content-Type: application/json
secret: {{rootSecret}}

{
  "id": 1,
  "content": "editedFirstChatFirstThreadFirstMessage"
}

### REMOVE
DELETE {{baseUrl}}/message
Content-Type: application/json
secret: {{rootSecret}}

{
  "id": 38
}

### GET
GET {{baseUrl}}/message?step=2&orderDirection=middle&id=15
Content-Type: application/json
secret: {{localRootSecret}}

### GET
GET {{baseUrl}}/getAllMessages?chatID=11
Content-Type: application/json
secret: {{rootSecret}}