### ADD
POST {{baseUrl}}/message
Content-Type: application/json
secret: {{rootSecret}}

{
  "chatID": 10,
  "content": "hello"
}

### EDIT
PATCH {{baseUrl}}/message
Content-Type: application/json
secret: {{rootSecret}}

{
  "id": 1,
  "content": "editedFirstChatFirstThreadFirstMessage"
}

### REMOVE
DELETE {{baseUrl}}/message
Content-Type: application/json
secret: {{rootSecret}}

{
  "id": 1
}

### GET
GET {{baseUrl}}/message?id=1&orderDirection=asc&step=5
Content-Type: application/json
secret: {{rootSecret}}

### GET
GET {{baseUrl}}/getAllMessages?threadID=1
Content-Type: application/json
secret: {{rootSecret}}