### ADD
POST {{baseUrl}}/message
Content-Type: application/json
secret: {{localRootSecret}}

{
  "chatID": 2,
  "content": "replyContent",
  "reply": "14"
}

### EDIT
PATCH {{baseUrl}}/message
Content-Type: application/json
secret: {{rootSecret}}

{
  "id": 1,
  "content": "editedFirstChatFirstThreadFirstMessage"
}

### REMOVE
DELETE {{baseUrl}}/message
Content-Type: application/json
secret: {{rootSecret}}

{
  "id": 38
}

### GET
GET {{vpsUrl}}/message?step=10&orderDirection=desc&id=1292
Content-Type: application/json
secret: {{vpsRootSecret}}

### GET
GET {{vpsUrl}}/getAllMessages?chatID=39
Content-Type: application/json
secret: {{vpsRootSecret}}