### ADD
POST {{baseUrl}}/thread
Content-Type: application/json
secret: {{rootSecret}}

{
  "title": "first thread",
  "chatID": 21
}

### GET
GET {{baseUrl}}/thread?start=0&step=5&chatID=21
Content-Type: application/json
secret: {{toorSecret}}