### ADD
POST {{baseUrl}}/thread
Content-Type: application/json
secret: {{rootSecret}}

{
  "title": "third thread",
  "chatID": 1
}

### GET
GET {{baseUrl}}/thread?start=0&step=-1&chatID=1
Content-Type: application/json
secret: {{rootSecret}}